server:
  port : 8080
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    url: ${PSQL_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${PSQL_USERNAME:postgres}
    password: ${PSQL_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  flyway:
    datasource:
      locations: classpath:/db/migration
      baseline-on-migrate: false
      validate-on-migrate: true

mbn-ui:
  url: ${MBN_UI_BASE_URL:#{"http://localhost:3000"}}

mbn-images:
  save-path: ${MBN_SAVE_IMAGE_PATH:#{"./"}}
  get-gdpr-path: ${MBN_GET_GDPR_PATH:#{"./src/main/resources/static/documents/GDPR/GDPR.pdf"}}


