server:
  port : 8090
spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: alina
    password: alina
    driverClassName: org.postgresql.Driver
  flyway:
    datasource:
      locations: classpath:/db/migration
      baseline-on-migrate: false
      validate-on-migrate: true

mbn-ui:
  url: ${MBN_UI_BASE_URL:#{"http://localhost:3000"}}

mbn-images:
  save-path: ${MBN_SAVE_IMAGE_PATH:#{"/Users/albica/Desktop/mbn/mbn-service/src/main/resources/static/documents/"}}
  get-gdpr-path: ${MBN_GET_GDPR_PATH:#{"/Users/albica/Desktop/mbn/mbn-service/src/main/resources/static/documents/GDPR/GDPR.pdf"}}


